services:
  db-django:
    image: postgres
    restart: always
    volumes:
      - db-django:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: "redis:latest"
    volumes:
      - redis:/data

  django:
    build: django
    ports:
      - "8000:8000"
    volumes:
      - ./public:/public
      - ./django:/app
    environment:
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=True
      - STATIC_HOST=localhost:8080
      - STATIC_PROTOCOL=http
      - DJANGO_HOST=localhost
      - POSTGRES_NAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TRUSTED_ORIGINS=${DJANGO_TRUSTED_ORIGINS}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db-django
      - redis

  nginx:
    image: nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./public:/public
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=_
      - NGINX_PORT=80

volumes:
  db-django:
  redis:
